baseURL = "https://crawfordlong.com/"
uglyURLs = false
disableKinds = ["section"]
title = "crawfordlong.com"
buildFuture = true

[pagination]
pagerSize = 12

[permalinks]
photos = "/:2006/:01/:02/:1504-:slug/"
notes  = "/:2006/:01/:02/:1504-:slug/"

[imaging]
resampleFilter = "Lanczos"

[taxonomies]
tag = "tags"


