publish_mode: editorial_workflow
show_preview_links: true
backend:
  name: github
  repo: crawfordlong/crawfordlong-com-2025
  branch: trunk
  base_url: https://www.crawfordlong.com
  auth_endpoint: /api/auth
  squash_merges: true
  preview_context: 'cloudflare preview deploy'
  
site_url: https://crawfordlong.com
display_url: https://crawfordlong.com

# collections keep media next to the entry (leaf bundles)
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: photos
    label: Photos
    folder: "content/photos"
    create: true
    path: "{{year}}/{{month}}/{{day}}/{{hour}}{{minute}}-{{slug}}/index"
    media_folder: ""      # upload beside index.md
    public_folder: ""
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    editor:
      preview: true
    fields:
      - {name: title, widget: string, required: true}
      - {name: date,  widget: datetime}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {name: caption, widget: string, required: false}
      - {name: image, label: Cover Image (optional), widget: image, required: false}
      - {name: body, widget: markdown, required: false}
  - name: notes
    label: Notes
    folder: "content/notes"
    create: true
    path: "{{year}}/{{month}}/{{day}}/{{hour}}{{minute}}-{{slug}}/index"
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    editor:
      preview: true
    media_folder: ""
    public_folder: ""
    fields:
      - {name: title, widget: string, required: true}
      - {name: date,  widget: datetime}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {name: body, widget: markdown}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
